services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: online_store   # Прямо указываем значение
      POSTGRES_USER: postgres     # Прямо указываем значение
      POSTGRES_PASSWORD: 123456   # Прямо указываем значение
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_NAME: online_store
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_HOST: my-postgres
      DB_PORT: 5432
      SECRET_KEY: random_secret_key123
      SECRET_REFRESH_KEY: random_refresh_secret_key123
      EMAIL_USER: dilbartalantova@gmail.com
      EMAIL_PASS: gkwy iphe bofh delq
    volumes:
      - ./server:/app
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "dev"]
    depends_on:
      - db
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge
